### ISSUE TITLE
German Ligatures broken with fat font in xetex

### ISSUE THREAD

**Issue by dasteihn** [psb1558/Junicode-font#102]
![junicode-broken](https://user-images.githubusercontent.com/28155519/154817181-1b7c107e-3801-4ee1-ab8e-c536040c9c26.png)

TeX to reproduce:
```
\documentclass[12pt, a4paper, ngerman]{scrartcl}
\usepackage{graphicx}

\usepackage{fontspec, ngerman}
\setmainfont{Junicode}

\selectlanguage{ngerman}


\begin{document}
\begin{titlepage}
{
	\Large\bfseries
	Breitbandempfänger
}

\end{titlepage}
\end{document}
```

Xelatex-Version:

```
xelatex --version
XeTeX 3.141592653-2.6-0.999993 (TeX Live 2021/Arch Linux)
kpathsea version 6.3.3
Copyright 2021 SIL International, Jonathan Kew and Khaled Hosny.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the XeTeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the XeTeX source.
Primary author of XeTeX: Jonathan Kew.
Compiled with ICU version 70.1; using 70.1
Compiled with zlib version 1.2.11; using 1.2.11
Compiled with FreeType2 version 2.11.1; using 2.11.1
Compiled with Graphite2 version 1.3.14; using 1.3.14
Compiled with HarfBuzz version 3.2.0; using 3.2.0
Compiled with libpng version 1.6.37; using 1.6.37
Compiled with pplib version v2.05 less toxic i hope
Compiled with fontconfig version 2.13.94; using 2.13.94
```

**Comment by psb1558** [comment]
I take it you're using version 1.003 and not the very old version packaged with TeX distributions. Not that it matters: it's not working in 1.003 either, and for the moment, anyway, I'm not sure why, since the rule is present in Bold exactly as it is in Regular (where it works well).

I've got a workaround for you while I try to fix the problem (don't know how long it will take). It's below, but a quick word of explanation. What's _supposed_ to happen isn't a ligature but a contextual substitution: **f** becomes a narrow **f** when followed by certain vowel + diacritic combinations, and then a little kerning is applied to clean up. You can emulate this behavior with this command:

```
\newcommand\fadieresis{\XeTeXglyph 491\kern+0.8pt ä}
```

(This will work _only_ with the bold face in version 1.003.) Fiddle with the kerning until it looks good to you, and then `Breitbandemp{\fadieresis}nger`  will give you the right result.
<img width="528" alt="image" src="https://user-images.githubusercontent.com/16215767/154820225-64d089a7-b985-4a8c-8244-73a33eba7f1e.png">
I'll leave a comment and close the issue when (if) I figure out what's going wrong and how to fix it.

**Comment by kenmcd** [comment]
> I'll leave a comment and close the issue when (if) I figure out what's going wrong and how to fix it.

In the Bold font that replacement is missing in the DFLT localization.
It is in the latn so when that is selected it works in the Bold.
In the Regular that replacement is in both the DFLT and latn.
So if you add it into the DFLT in the Bold it should work as expected.

**Comment by psb1558** [comment]
Thanks for the diagnosis, @kenmcd! I'll see if I can make the change in the TTX. Or maybe I'll make a UFO and operate on that.

**Comment by psb1558** [comment]
There's a new version of Junicode-Bold in the "Junicode One" branch of the repository. With script and language  tags fixed, it seems to work okay. In the repository, switch to the "Junicode One" branch and grab Junicode-Bold.ttf from the "legacy" folder. The others haven't changed.

Check in here if you have any difficulties.

**Comment by dasteihn** [comment]
Thx for the very quick fix!
Is this going into master or will it stay in the One-Branch?

**Comment by psb1558** [comment]
It's not a problem with Junicode Two (where all weights are built from the same code, derived ultimately from the Regular). So no changed needed in master branch.

<img width="369" alt="image" src="https://user-images.githubusercontent.com/16215767/154840452-f389290e-93b4-4e65-8d39-c6b630fbcd9f.png">
