### ISSUE TITLE
Tildes are too shallow

### ISSUE THREAD

**Issue by TheKnightWho** [psb1558/Junicode-font#117]
Hi - at the moment tildes seem to be very shallow - particularly U+360 (double combining tilde). At smaller sizes, they become hard to distinguish from macrons.
![image](https://user-images.githubusercontent.com/6895210/157382473-2be218b2-fd95-4ddb-bc1a-e1c4e5718467.png)
Would it please be possible to adjust the peaks to something similar to the tilde on the new double l ligature? It's much easier to make out.
![image](https://user-images.githubusercontent.com/6895210/157382751-3d4150cb-a563-41ca-ba48-4005203e3c74.png)
Compare with the other tildes in the below:
![image](https://user-images.githubusercontent.com/6895210/157383148-e4141c5c-e2b0-48a0-b029-d8a9836bb373.png)

**Comment by psb1558** [comment]
The double tilde needs some attention, but with the others the problem is poor hinting, because at present the static fonts  are hinted with ttfautohint, without deltas or other interventions. I need to see if I can fix with control instructions for ttfautohint or, if that fails, a patch.

The tilde is an endlessly troublesome glyph--at least when rendered on screen.

**Comment by psb1558** [comment]
I have made new hints for the lowercase tilde. See if it improves anything.

**Comment by psb1558** [comment]
Since I haven't heard differently, I'll suppose (hope?) the revised hints have done the trick.
