### ISSUE TITLE
zigzags

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-font#130]
### Discussed in https://github.com/psb1558/Junicode-font/discussions/95

F1C8 COMBINING ABBREVIATION MARK ZIGZAG ABOVE CURLY FORM has the shape different than Combining curly zigzag created with U+0304 and 05 tags. Is this intentional?
![JSBcurlyzigzag](https://user-images.githubusercontent.com/8024702/160597380-73e20ef4-f36c-4643-a935-4c7b66794186.png)

**Comment by psb1558** [comment]
No -- I'll change it. Remember, though, that U+F1C8 is pretty much useless because many apps will fail to position it properly on the base letter. Also, it won't vary contextually the way Junicode's curly zigzags do.

I should mention, too, that I haven't yet thoroughly investigated the interactions of combining marks produced via tags with other OpenType features—especially a few things like the zigzag, which is a complex system. I'm sure I'm going to encounter bugs needing fixing.

**Comment by psb1558** [comment]
That said, so far the tags seem to be working well with the contextual feature:
<img width="532" alt="image" src="https://user-images.githubusercontent.com/16215767/160602015-9bb9ad22-c0c3-403c-83a1-7333ebe97621.png">

**Comment by psb1558** [comment]
This is fixed now.
