### ISSUE TITLE
Diacritic symbols and copy machine

### ISSUE THREAD

**Issue by dfballes** [psb1558/Junicode-font#138]
Good morning.

The copy machine at my school won‘t print diacritic symbols correctly, they are all shifted to the left (see picture). My printer at home prints them the right way. Before I report that to the distributor of the copy machine: Is there any chance, that this is a problem of the font? As I can see it, it‘s the only font that has this issue (at least the only one I tested. Times New Roman for example prints just fine.).

Best regards,
Daniel
![61AB9D0B-BF04-431F-AED8-CDB7FFA8C444](https://user-images.githubusercontent.com/72363366/171564493-51c5f9ea-ed82-404e-bb3c-bb2894f36049.jpeg)

**Comment by psb1558** [comment]
This is, I understand, a bug in some printer drivers, affecting glyphs made of components in ttf fonts. I don't know why it affects some fonts and not others, or why the bug has been around for years without a fix. The easiest solution is to grab the otf version and use that, since otf fonts don't use components.
