### ISSUE TITLE
Italic fi ligature bug

### ISSUE THREAD

**Issue by Elendil03** [psb1558/Junicode-font#155]
<img width="40" alt="fi" src="https://user-images.githubusercontent.com/51972670/209559718-0acea13b-d109-43eb-aeda-44f389fd9137.png">

<img width="40" alt="fi word" src="https://user-images.githubusercontent.com/51972670/209560392-19c4de1e-0b3d-478f-950e-d583c28445f3.png">

The first one is in LibreOffice, the second one in Word (with ligatures and CALT enabled). Left is always Junicode Two, right is Junicode One. I used the Bold Italic font in the former and Regular Italic in the latter, but the problem occurs in both fonts on both word processors.
There is a visible bend where the f and the i meet, noticeable especially at larger point sizes, though it disappears when zooming in.

**Comment by psb1558** [comment]
Instead of traditional ligatures, a number of modern fonts use contextual alternates to construct ligatures, e.g. a shape of f used when i is the next letter and a shape of i used when f is the previous letter:
<img width="76" alt="image" src="https://user-images.githubusercontent.com/16215767/209608424-3d4d0ed6-7739-47a3-8f06-a34f816946e8.png"> which becomes 
<img width="63" alt="image" src="https://user-images.githubusercontent.com/16215767/209608626-396c6035-ed3b-4d98-a822-e1673306d979.png">
Here the bars of the f and the i are not joining cleanly, though they are are exactly the same height. This is probably because the hints are faulty. I'll see what I can do. Meanwhile, this will probably happen only at certain resolutions and on certain systems or displays.

**Comment by Elendil03** [comment]
I see. What's the advantage compared to regular ligatures?

**Comment by psb1558** [comment]
These should be fixed in the fonts now in the repository (version 1.055). What's chiefly gained by this new system is flexibility. For example, when someone recently asked for long **s** to ligature with following **ł**, it was dead easy to supply that with one new base character (as opposed to two or more new ligature characters).
