### ISSUE TITLE
Kerning between V/W and lower case letters is a bit too wide, isn't it? Here's a comparison.

### ISSUE THREAD

**Issue by dawidd4** [psb1558/Junicode-font#179]
![Junicode 2 Beta Light Condensed 1 057](https://github.com/psb1558/Junicode-font/assets/40753083/2f6d2a9b-b669-4707-abc4-cf3d624593d9)

**Comment by psb1558** [comment]
That looks bad. I'll fix it.

**Comment by dawidd4** [comment]
I'm thinking that some Upper Case letters could be also more condensed in the condensed font style. Comparing to other condensed font families the glyph spacing is a little bit too wide.
Instrument Serif is also for free, but the condensed style is the default one. But the characteristic of this font lies in its long tails of the letters "R" "a", etc. It has one of the most condensed W's.

**Comment by psb1558** [comment]
The kerning is fixed. I'll think about the widths of condensed caps.

**Comment by dawidd4** [comment]
I must apologize. It's MS Paint that creates the unusual letter spacing. Glyphs there start always at the same pixels: https://github.com/Instrument/instrument-serif/issues/4

**Comment by psb1558** [comment]
Actually, there was a problem with kerning of sequences like VA, WA, TA, Wa, Va, Ta. That's fixed now, with suitable exceptions for vowels with accents.

But I'm not surprised that MS Paint does its spacing oddly. It has been around since [Windows 1.0 in 1985](https://en.wikipedia.org/wiki/Microsoft_Paint). I imagine it has done its own rasterizing from the beginning--and Microsoft is notorious for hanging onto extremely ancient code in its Windows apps and Office suite.
