### ISSUE TITLE
Weirdness with combining above diacritics when there are diacritics below

### ISSUE THREAD

**Issue by leafpool243** [psb1558/Junicode-font#238]
![圖片](https://github.com/psb1558/Junicode-font/assets/63614345/1bc9b534-c87b-4101-bd19-587eceae5f2c)

All “i's” with a diacritic below have an extraneous tittle when a diacritic is added above.

```latex
\documentclass[14pt]{article}
\usepackage{fontspec}
\setmainfont[BoldFont=*,
BoldFeatures={RawFeature={axis={wght=700}}},
ItalicFont=*-Italic,
BoldItalicFont=*-Italic,]{Junicode VF}
\begin{document}
\noindent i í ì î ï ĩ\\
ị ị́ ị̀ ị̂ ị̈ ị̃\\
ḭ ḭ́ ḭ̀ ḭ̂ ḭ̈ ḭ̃\\
į į́ į̀ į̂ į̈ į̃\\
\end{document}
```

**See related issue over at Elstob:** psb1558/Elstob-font#36

**Comment by psb1558** [comment]
This is a by-product of normalization, a function of the layout engine (e.g. HarfBuzz): where possible, the layout engine substitutes composite glyphs (e.g. **ị** U+1ECB) for sequences like **i + combining dot below**, and because this is *before* the programming in the font is ever executed, the font can't prevent it.

The usual thing is that when the font sees a sequence like **i + combining acute accent**, it substitutes a dotless form of **i** for **i**. But the font *does not* contain a dotless form of **ị**, which would be used only in a few edge cases.

Some fonts (e.g. Gentium) contain a workaround for this particular case, while others (e.g. Brill) leave users to puzzle it out for themselves. My sense is that there are a great many cases where normalization will get in the way of setting the exact sequence you want. The Junicode Manual discusses several of these, and it recommends placing the COMBINING GRAPHEME JOINER U+034F between the base character and the first diacritic to prevent normalization. That is the approach that Junicode and Elstob recommend.

Unfortunately, both Junicode and Elstob also have errors and/or omissions that keep U+034F from working properly in this particular case. The fix will be in Junicode version 2.005, probably in about a week, and in the Elstob repository very soon. After that, the sequence **i U+034F U+0323 U+0301** will yield what you want, while the sequence **i U+0323 U+0301** willl produce a dotted i:
<img width="87" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/94e70081-531c-498f-8bf2-c7fa2c3884f1">

**Comment by psb1558** [comment]
With the fixes in v2.005, this file
```
\documentclass[14pt]{article}
\usepackage{fontspec}
\setmainfont[BoldFont=*,
BoldFeatures={RawFeature={axis={wght=700}}},
ItalicFont=*-Italic,
BoldItalicFont=*-Italic,
RawFeature={mode=harf}]{Junicode VF}
\begin{document}
\noindent i í ì î ï ĩ\\
i\char"0323\ i\char"034F\char"0323\char"0301\ i\char"034F\char"0323\char"0300\ %
     i\char"034F\char"0323\char"0302\ i\char"034F\char"0323\char"0308\ i\char"034F\char"0323\char"0303\\
i\char"0330\ i\char"034F\char"0330\char"0301\ i\char"034F\char"0330\char"0300\ %
     i\char"034F\char"0330\char"0302\ i\char"034F\char"0330\char"0308\ i\char"034F\char"0330\char"0303\\
i\char"0328\ i\char"034F\char"0328\char"0301\ i\char"034F\char"0328\char"0300\ %
     i\char"034F\char"0328\char"0302\ i\char"034F\char"0328\char"0308\ i\char"034F\char"0328\char"0303\\
\end{document}
```
willl yield this result:
<img width="90" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/5b503005-5957-4ebb-a77f-f1f5e45fc5c4">

Elstob will have similar fixes.

Anyone who works with unusual combinations of diacritics needs to be aware of U+034F, which is nothing more than a zero-width combining mark without visible outlines. Its purpose is to break apart sequences containing combining marks so that (for example) normalization will not take place when the layout engine encounters a base+mark sequence that is canonically equivalent to a Unicode composite character.

A well-behaved search function will ignore U+034F.

**Comment by leafpool243** [comment]
Thank you! This is quite interesting.

**Comment by psb1558** [comment]
See if version 2.100 (released today) works for you.
