### ISSUE TITLE
Default figures should be proportional - like v1

### ISSUE THREAD

**Issue by kenmcd** [psb1558/Junicode-font#239]
Today I was looking at some sample text I had created for Junicode v1 - and it looked wrong.
The dates all looked bad.
So upon investigation I discovered the default figures are now tabular lining.
In v1 the default figures are proportional lining (which makes more sense).
So anyone moving from Junicode v1 to Junicode v2 is in for a shock.

I do not see Junicode as some office suite utility font.
Tabular lining is appropriate in that case.
But Junicode is for replication/transcribing of old long-form text.
At a minimum the default figures should be proportional, and probably the default should be oldstyle proportional.

In long-form text I always use oldstyle proportional figures, which is the best thing for high-quality text - it is what you are going to see in high-quality books.
So I usually have to set-up a character style to fix the dates, etc.
Today I had to use `Junicode:onum&pnum` in LibreOffice
to get text quality figures.

Many high-quality text fonts have oldstyle proportional as the default figures. When you are writing a lot of long-form text why should the writer constantly have to "fix" all the figures?

Some OFL Google fonts with oldstyle proportional as default:
Alegreya
Alegreya Sans
Coelacanth Garamond
Cormorant
EB Garamond
... (I just started down the list)
Playfair  (he told them No)
and many more.

And lots of fonts in Google Fonts have proportional lining as the default.
They like to have tabular lining as the default, but many fonts just say No.
In many cases it just does not make sense.

Given the target use of Junicode I would make the default figures oldstyle proportional.
But at the very minimum I think you should go back to proportional lining as the Junicode v2 default figures.

Note: there are also a number of commercial fonts with oldstyle proportional as the default figures - usually marketed as high-end text fonts.

**Comment by psb1558** [comment]
Proportional lining figures have never been the default in Junicode, but always tabular lining. Do you have your software set to apply `pnum` as the default?

That said, it's a fact that almost every time I set up a document, I turn on `pnum` and `onum`, and it's true that figures in the kind of document that Junicode targets are most likely to appear in a prose context. If it's not too disruptive to existing users, I'll change the default to proportional oldstyle in the next release.

**Comment by kenmcd** [comment]
Great.
I suspect we are not the only users who do this.
And this will be a welcome change to most users.

Hmmm... will check again tomorrow, but I think I was looking at the last v1 in FontCreator (where I typically check OpenType stuff).

**Comment by Doc73** [comment]
Sorry for this post, but in XeLaTeX at least it seems that the default for this font is lnum+tnum.
I am a fanatic user of onum, but I think it would be more prudent to set lnum+pnum as the default settings.

```tex
% !TeX TS-program = xelatex
% !TeX encoding = UTF-8
% !TeX spellcheck = it_IT
% !TeX root = Junicode-numbers.tex

\documentclass[11pt,b5paper,article]{memoir}
\usepackage{fontspec,unicode-math}
\setmainfont[]{Junicode}
\usepackage{hyperref}

\begin{document}
\begin{tabular}{lll}
  1234567890 & default & lining+tabular?\\
  {\addfontfeatures{RawFeature=+lnum}1234567890} & lnum & lining+tabular?\\
  {\addfontfeatures{RawFeature=+tnum}1234567890} & tnum & lining+tabular?\\
  {\addfontfeatures{RawFeature=+pnum}1234567890} & pnum & lining+proportional?\\
  {\addfontfeatures{RawFeature=+lnum;+pnum}1234567890} & lnum+pnum & \\
  {\addfontfeatures{RawFeature=+lnum;+tnum}1234567890} & lnum+tnum & \\
  {\addfontfeatures{RawFeature=+onum}1234567890} & onum & oldstyle+tabular\\ 
  {\addfontfeatures{RawFeature=+onum;+pnum}1234567890} & onum+pnum & \\ 
  {\addfontfeatures{RawFeature=+onum;+tnum}1234567890} & onum+tnum & \\ 
\end{tabular}
\end{document}

%%% Local Variables:
%%% coding: utf-8
%%% mode: latex
%%% TeX-engine: xetex
%%% TeX-output-dir: "junicode-numbers"
%%% TeX-master: t
%%% End:
```

**Comment by psb1558** [comment]
I've never been very fond of proportional lining numbers. Seems to me the only place they make any sense is in an all-caps context, and how much of a typical project is all caps? I'm still leaning towards proportional oldstyle as the default.

**Comment by Doc73** [comment]
Ok! For me proportional+oldstyle is fine as default. :+1: 

In the meanwhile, I tested other fonts with previous MWE. Here are the default settings:
- Brill: oldstyle + proportional
- Minion Pro: lining + tabular
- Libertinus Serif: lining + tabular

**Comment by kenmcd** [comment]
> Seems to me the only place they make any sense is in an all-caps context

Quite a few fonts include proportional lining figures in their Case Sensitive Forms `case` feature. 
For example:
Playfair - the default oldstyle proportional is converted to lining proportional when `case` is applied
STIX Two Text - converts their default tabular lining, and oldstyle figures to proportional lining when `case` is applied.
Alegreya- `case` converts figures to proportional lining
Cormorant Garamond - `case` converts figures to proportional lining
Literata - `case` converts figures to proportional lining
Merriweather - `case` converts figures to proportional lining
Noto Serif - `case` converts figures to proportional lining
Source Serif 4 - `case` converts figures to proportional lining
and many more...

You are not alone in the opinion that proportional lining figures are appropriate in all-caps text.
So you may want to add that to the Junicode `case` feature.

**Comment by psb1558** [comment]
Lining figures have been in `case` for a while (I'm not sure how long--don't remember when I added those rules).

`case` and a number of other features are touched by this change: sups, subs, frac, zero . . . I'm hunting them down right now. It will have to be tested carefully.

**Comment by kenmcd** [comment]
Regarding the `one` style in the oldstyle figures:

A few "old style" fonts who are trying to stay true to their roots use the old style `one` (which looks like a short capital I).
Most newer text fonts use the more modern flagged one (which looks like a short one).
Some fonts give user the option of using either form.

Old style one as default in oldstyle figures:
Cormorant Garamond
EB Garamond

Modern flagged one as default in oldstyle figures:
Alegreya
Besley
Bookmania (commercial)
Crimson Pro
Georgia Pro (commercial)
LibreCaslon Text
Literata
Merriweather
Noto Serif
Palatino (commercial)
Playfair
Source Serif 4
STIX Two Text

Grad (commercial) - default is old style, modern style is `ss02`
Vollkorn - default is old style, modern style is `ss11`
XCharter - default is old style, modern style is `cv01`
and I have seen quite a few others which give users the option.

For my use, I would prefer the modern one as the default in the oldstyle figures, because I am writing modern text not transcribing old text.
But the old style one may be more appropriate as the default one in the oldstyle figures for the Junicode target audience of "medievalists" who may prefer that old style one.
Dunno.
Leave that one up to you.
But it would me nice if both versions of the one were available in the oldstyle figures.

**Comment by kenmcd** [comment]
> Lining figures have been in `case` for a while (I'm not sure how long--don't remember when I added those rules).

Hmmm... I am not seeing this being applied when testing in FontCreator OpenType designer.
I can see the feature there - but nothing happens.
Have to investigate further...

**Comment by kenmcd** [comment]
The oldstyle `zero.osf` and `zero.tosf` need some contrast like the normal `zero`.
It looks odd as simple ring.

**Comment by psb1558** [comment]
Fonts differ here. In the model for Junicode, the zero is a simple ring:
<img width="516" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/8d67bf34-35dd-4f1e-9dae-fca2244aa77c">
In Adobe Garamond, which was influential with me back in the day, the zero is a nearly perfect circle, and not only is there no contrast, there's not even optical correction of stem weights. Plus, the weight of the zero is not made to match that of other figures:
<img width="178" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/117286cd-711a-4735-aed7-4c7be5c13bbb">
I believe this aspect of the Adobe font is historically accurate, though it is a little jarring. Less historically oriented fonts (e.g. Brill, Libertinus) do not tolerate this, but weight the zero like the other figures.

I thought about this many ages ago, when I was designing these numbers, and decided to stay with the old style, but do optical correction (unlike the Garamond):
<img width="196" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/ea9ce48b-bd39-4bc5-b41e-21f6e9a8159a">
I'm still comfortable with this choice.

**Comment by psb1558** [comment]
In old books the one is, I believe, always I-like. I've been meaning to add the flagged form as an alternate for some time. Perhaps this is the week it gets done!

**Comment by kenmcd** [comment]
> I believe this aspect of the Adobe font is historically accurate, though it is a little jarring. Less historically oriented fonts (e.g. Brill, Libertinus) do not tolerate this, but weight the zero like the other figures.

Perhaps add an alternate with contrast for users writing modern text. In a normal context (not historical text) it is "jarring" and the font looks broken. I was not aware of this old format and to my non-medievalist eye it just appears wrong. Same issue I suppose with the ring on the Aring in some fonts. Just looks odd in normal text.

**Comment by psb1558** [comment]
Maybe I could put the zero on the same OT feature as the flagged one. `ssNN` and `cvNN` features are getting kind of hard to come by. Or maybe there's some suitable number-specific feature I haven't noticed yet.

**Comment by kenmcd** [comment]
ss21 is open.  <grin>

**Comment by psb1558** [comment]
Last resort.

**Comment by psb1558** [comment]
Actually, ss09 is also open. I was reserving it for language-specific variants, but in practice it has proved a better idea to create language-specific variants within other features (ss02 behaves differently depending on whether the language is English or Irish—there may be more like that in the future).

So ss09 might be perfect for "Alternate Figures." Are there others I should be thinking about?

**Comment by kenmcd** [comment]
> So ss09 might be perfect for "Alternate Figures." Are there others I should be thinking about?

Have a few ideas.
Will also look at some "it has everything" fonts.
Will not be at my computer for an hour or so.
On my phone at the moment.

**Comment by psb1558** [comment]
Here's a first go at flagged one:
<img width="302" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/78ac531e-5140-4304-b3c3-ba377c47d920">
1. proportional oldstyle (the default)
2. default + ss09
3. default + ss09 + tnum

**Comment by psb1558** [comment]
And zero. The proportional and fixed-width zeroes are the same, but every style of zero in Junicode  needs a slashed version.
<img width="260" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/2a15c5ed-999f-471f-a784-31eaba46e035">

**Comment by kenmcd** [comment]
> Here's a first go at flagged one: <img alt="image" width="302" src="https://user-images.githubusercontent.com/16215767/269061537-78ac531e-5140-4304-b3c3-ba377c47d920.png">
> 
>     1. proportional oldstyle (the default)
> 
>     2. default + ss09
> 
>     3. default + ss09 + tnum

The flag seems a bit long and thin.
I like to see the one as a shorter lining proportional one,
but optically adjusted for the size.
Flag a little shorter and a little thicker.
Serifs a little thicker.
Sort of the same way the one superscript would be optically adjusted for the downsize.

zero is perfect.

**Comment by psb1558** [comment]
The oldstyle ones in the fonts I surveyed almost all had flags wider than the serif (sometimes extravagantly so), e.g.
<img width="943" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/124278e1-86c8-4d06-bee0-141cb34a4737">
That also struck me as a little odd at first, but I think I understand the design problem it addresses: it's hard to make a one fill the space it needs to fill—especially, but not exclusively, the tabular form.

I'll work on the weight of the flag and serif.

**Comment by psb1558** [comment]
This time the flag is a *tiny* bit shorter, but mainly it's significantly thicker. Maybe that makes it look a little shorter too.
<img width="232" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/1ad0282c-deb6-4a85-a2bd-cf87b668600e">

**Comment by kenmcd** [comment]
> This time the flag is a _tiny_ bit shorter, but mainly it's significantly thicker. Maybe that makes it look a little shorter too. <img alt="image" width="232" src="https://user-images.githubusercontent.com/16215767/269148760-1ad0282c-deb6-4a85-a2bd-cf87b668600e.png">

I like it.

**Comment by psb1558** [comment]
I've posted variable fonts (only) with the changes we've been discussing in the `fonts` directory (no release yet). Since these changes are substantive and highly visible, I'm bumping the version number to 2.100 (for now followed by RC numbers). Here's a summary of the changes:

- proportional oldstyle figures now the default.
- use `lnum` to get lining figures, `tnum` for tabular (fixed width).
- ss09 produces alternate shapes of oldstyle zero and one (including super- and subscripts and slashed zero).
- in super- and subscripts there are (as before) only proportional oldstyle and tabular lining forms.
- in fractions there are only tabular lining forms (but I am thinking of adding proportional oldstyle).

The number system is suprisingly complex, involving over 200 glyphs and at least twelve OT features. Lots of opportunities for me to make mistakes. So I'll be grateful for any checking that folks can do.

**Comment by kenmcd** [comment]
OK. Really like having oldstyle proportional as the default.

Started looking and testing...

Expected the Oldstyle Tabular and the Lining Tabular to be the same width (as in other fonts).
The Oldstyle Tabular seems really wide (loose).

![Oldstyle vs Lining Tabular 2023-09-22_15-24-25](https://github.com/psb1558/Junicode-font/assets/844920/471ff321-9648-4c22-b050-665c0ed73231)

**Comment by kenmcd** [comment]
Oldstyle Flagged One Spacing and Kerning
This is the Italic.
For example in the GIF below the one appears to be a bit too far from the two - it does not have that top-right serif to make it look closer.
And the two ones in 1811 appear to be a bit loose.
The Roman has some similar issues.
Perhaps take a look at the spacing/kerning on both sides of the flag one.

![Oldstyle Flagged One Spacing 2023-09-22_15-41-30](https://github.com/psb1558/Junicode-font/assets/844920/ecc6651b-4d1c-4582-aa50-dd0a964221d1)

**Comment by psb1558** [comment]
Thanks for these pointers. I think I see what to do. Will report back.

**Comment by psb1558** [comment]
Another go at revised numbers in the repository. I confess that I've never taken numbers seriously enough--never thought of them as a system as opposed to a collection of (somewhat boring) isolated glyphs. Now I'm taking care of that. Also some of the outlines are seriously in need of revision, and I'll be addressing that before I make another release.

**Comment by psb1558** [comment]
Okay, version 2.100 RC 3 is now in the repository. Most of the work here has gone into making sure tabular figures are always the same width and there is consistency of size and positioning across the font. Also a certain amount of outline revision.

You can get superscript and subscript numbers in either of two ways: applying `sups` or `subs` to plain numbers or entering the Unicodes for superscripts and subscripts. Either way, the number features affect these characters in a limited way. Use `lnum` to shift from oldstyle to lining numbers--but `pnum` and `tnum` have no effect on superscripts or subscripts.

**Comment by kenmcd** [comment]
v2.100.RC3.(2023-09-25).from.repo

![It was the year 1941](https://github.com/psb1558/Junicode-font/assets/844920/f893c40d-a439-40ac-8057-c20b2ea9f2d4)

That looks really good.

Will do some more feature testing tomorrow. 
Kinda fading now...

**Comment by kenmcd** [comment]
Please consider more adding more currency symbols to Oldstyle.

Junicode 2.100.RC3
![onum-currency-Junicode 2023-09-27_11-20-04](https://github.com/psb1558/Junicode-font/assets/844920/a9e2bfba-c70d-46e8-beab-ef6b8fb48145)

STIX Two Text
![onum-currency-STIX Two Text 2023-09-27_11-21-42](https://github.com/psb1558/Junicode-font/assets/844920/a5101f74-f24a-48f8-b75e-8934937e7f38)

Cormorant Garamond
![onum-currency-Cormorant Garamond 2023-09-27_11-23-46](https://github.com/psb1558/Junicode-font/assets/844920/7afa62e8-3602-4469-b581-754c509b071f)

**Comment by psb1558** [comment]
Yes. An excellent idea.

**Comment by psb1558** [comment]
This is going to take a little while, but here's a downpayment.
<img width="179" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/46b58a2b-d83b-4c81-95fb-484e567df5b5">

**Comment by eclecticfluff** [comment]
I don’t currently have the most recent version of the font so sorry if it’s already there, but the percent sign could probably also do with a short Oldstyle form.

**Comment by psb1558** [comment]
This, and also numbersign. Am I missing anything else?

**Comment by eclecticfluff** [comment]
[Test pdf](https://github.com/psb1558/Junicode-font/files/12782794/Junicode.pdf)
The primes and single quote and degree symbol are too high, but there are other contexts like °C where they should not be lowered. The period and comma alongside the aforementioned symbols could do with having kerning pairs in numbers since presently they leave unsightly gaps. Lastly, while the plus sign looks perfect and most of the others fine, the minus sign is noticeably longer and higher than the equals sign. It seems to have the same shape as the en dash, so maybe both could be lowered and length shortened only on the former. Also, while I didn't include it, ‰ and ‱ could be modified alongside %. I hope helps with the number overhauls and isn't too daunting of a list.

**Comment by psb1558** [comment]
No, it's good. Thanks for taking the trouble!

**Comment by psb1558** [comment]
There's still lots to do (hinting, kerning, the italics) before release, but I think maybe this answers.
<img width="401" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/78a90e75-0010-4e54-b8cb-74515a199ab7">
**quoteright**, **degree**, and **endash** are contextual: you get the lower form of the first two when an oldstyle number precedes, and of the third when an oldstyle number both precedes and follows. The others are controlled by OT features exactly the way the figures themselves are—with `lnum`, `tnum`, etc.

**Comment by eclecticfluff** [comment]
That looks like a great start, but there are a few more contextual cases which should be considered. **Prime** should probably also vary contextually considering its use with letters. Also, **quoteright** needs some rather complicated contextual rules since it needs to work in the cases of 1’000, ’23, 2020’s, P’s, q’s, ‘quoted text 1’, and ‘1 quoted text’.

**Comment by psb1558** [comment]
Prime has lots of uses (math, linguistics ...), probably too many possible contexts to make a reliable rule for it. As it is now manually switchable, so that users can always get exactly what they want, perhaps it would be best not to try.

I'm now handling **minus**, **quoteright**, **degree**, and **endash** via substitutions, but it seems to me that contextual kerning is a better solution. I recognize the problems with **quoteright**: the question is how many cases to handle via contextual rules and how many to leave to the user (e.g. by placing a formatting mark before the **quoteright**). In particular:
- should the quoteright be lowered *before* an oldstyle number as well as after?
- would it be useful to suppress kerning in a sequence where a comma or period follows the quotation mark, e.g. `1’.`?
- If adequate contextual rules for **quoteright** can't be formulated, would it be better to make it manually switchable and leave the problem to users?

**Comment by psb1558** [comment]
I haven't actually located a font that bothers to adjust quoteright contextually.

**Comment by eclecticfluff** [comment]
I wouldn’t be opposed to not bothering to adjust the raised punctuation contextually, and instead compromising between the two height extremes. While it feels fine for quotation marks to sit above the adjoining text, to my eye the apostrophe looks odd when not going below the highest points of the adjoining characters. Quotation marks and apostrophes should probably always be kerned to what they are modifying, thus ’0 would be kerned and in the case of ‘0’, the closing quote would be kerned tightly to the zero, but and low punctuation kerned looser. Note that I am no typographer, and

**Comment by eclecticfluff** [comment]
Thinking on the case of the lowered apostrophe, I think a different lowered form would only work if used solely when intended as a thousands separator (which is a simple and consistent rule). The other cases also occur with lower case letters, so making the text harmonious by manually picking the hight per quote would be hard enough, let alone attempting anything automatic. A stylistic set to lower raised punctuation font-wide couldn’t hurt if you haven’t run out of those since such cases are probably a matter of taste anyways. Also, the rule for degree needs to be refined slightly as [the form 32°C is sometimes used](https://english.stackexchange.com/a/2805).

**Comment by psb1558** [comment]
I've been thinking for a long time about lowering the quotation marks (some fonts I admire, like Brill and Roboto Serif, have them about even with the tops of the capitals). The project is a bit daunting, since all the kerning pairs (over 500 of them!) have to be reviewed, but now it seems necessary . . .
<img width="391" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/c7df5fdf-7c0e-4575-ad0a-04902e8bc39e">

**Comment by eclecticfluff** [comment]
Before committing to something so drastic, I wouldn’t mind seeing how the current high quoteright looks like when kerned properly to the proceeding and following digits.

**Comment by psb1558** [comment]
This image shows the oldstyle proportional numbers with a general rule applied (that is, a quoteright both preceded and followed by a number is shifted right by 25 font units):
<img width="397" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/e3df09a1-5bb6-49a7-ae58-be22b7ab12f3">
But then there have got to be exceptions to the general rule, as you can see with sequences like `0’8`, `7’0`. Pair kerning won't work here: each exception needs its own contextual rule. You can see this with the sequence `1’0`, which looks bad with the general rule (below left). But you can't fix this with a rule for the sequence `’0`, because that would mess up the sequence `0’0`, which looks okay (or at least good enough) with the general rule (right). So `1’0` gets its own contextual rule (middle—the only exception I've put in the font so far).
<img width="299" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/9573e7ef-6cb4-46fd-9c44-9a85ef066097">
The same sort of thing will have to be done with the period and the comma. Before I have gone much farther with this kerning project, I'm going to consider myself committed to the newly positioned quotation marks in the font.

**Comment by psb1558** [comment]
Some fine-tuning to do, but it's not too bad!
<img width="627" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/3cafde4d-6d5f-434f-aec0-3febd123ad4e">

**Comment by psb1558** [comment]
Actually, iot doesn't appear necessary to do contextual kerning for periods and commas. Big relief.

**Comment by eclecticfluff** [comment]
Sorry for the delay in response. Thinking about the quote some more, I think high quotes can look good in old style numbers. In the following image, I replaced the zeros with lowercase O’s since they have kerning pairs. The quote appears to belong to the number rather than floating above it due to the quirks of human perception that give font designers headaches. 
![IMG_2334](https://github.com/psb1558/Junicode-font/assets/65306291/2b50e3e4-e0e7-4633-8b82-4dcf551af666)

**Comment by psb1558** [comment]
No problem—things move at a stately pace here at chez Junicode.

It may be that it would have been all right to leave the quotation marks high, but all in all I prefer the lower position and will leave them there.

**Comment by psb1558** [comment]
One more (hopefully last) test version: 2.100 RC 4.

**Comment by psb1558** [comment]
The changes discussed in this thread are in version 2.100, just now released.
