### ISSUE TITLE
Ancient Greek diacritics combining with Breve and Macron

### ISSUE THREAD

**Issue by Doc73** [psb1558/Junicode-font#240]
I would like to suggest an improvement about the positions of diacritics with breve and macron.
Here is a comparison with a font widely used by classical philologists, New Athena Unicode ([https://apagreekkeys.org/index.html](https://apagreekkeys.org/index.html)).

![Schermata del 2023-09-25 15-39-39](https://github.com/psb1558/Junicode-font/assets/1306260/10ec1408-ff99-4fa6-88fc-af943dff6364)

Yes, I know that other importan fonts, like Minion Pro, look very similar to Junicode in this respect, but New Athena Unicode (and [IFAOGrec Unicode](https://www.ifao.egnet.net/publications/publier/outils-ed/polices/#grec)) follows the conventions of Greek philologists.

Thank you very much for your attention and again for your great job!

**Comment by psb1558** [comment]
This already works in Junicode when done in the following way. First set the script for the text to `grek` and the language to `ELL` (or whatever you do to set the language in your particular app—it absolutely won't work if the language is not properly set). Then type the base character—alpha, iota, or upsilon. Then combining comma or reversed comma (U+0313, u+0314). Then grave or acute (U+0300, U+0301). For example (in LibreOffice):
<img width="345" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/4df3cd9d-bc9f-45a4-8243-26871496f336">
(This isn't working properly in the italic, and I'm trying to figure out why, since the OT code is supposed to be the same.) New Athena seems to be a paid product, so I can't get it, but this sequence doesn't work in IFAO-Grec:
<img width="46" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/f687fe21-0786-4218-b977-36f8b51ce425">
What do you type when working with Athena and IFAO-Grec?

**Comment by Doc73** [comment]
I must do other tests, but later, because now I'm busy.
However I see that there are problems on Libreoffice and probably a lot depends on the **way** and order of character insertion.
I'm testing these tools for Libreoffice:
- [https://members.hellug.gr/sng/ancientgreekoxt/index.html](https://members.hellug.gr/sng/ancientgreekoxt/index.html)
- [https://github.com/jeremymarch/hopliteKB-LibreOffice](https://github.com/jeremymarch/hopliteKB-LibreOffice)

I see that:

- Brill and New Athena Unicode (you could download it free here: [New Athena Unicode](https://apagreekkeys.org/NAUdownload.html))  works fine both with Greek and with Italian (my language)
- Junicode no; here a screencast:
[Video del 2023-09-27 11-05-00.webm](https://github.com/psb1558/Junicode-font/assets/1306260/2c8fac20-8d23-49d9-9c48-77859ed1fe26)

With Latex the situation is even worse. Here a MWE:

```tex
% !TeX TS-program = xelatex
% !TeX encoding = UTF-8
% !TeX spellcheck = it_IT
% !TeX root = Root.tex

\documentclass[14pt,b5paper,article]{memoir}
\usepackage{fontspec}
\setmainfont[]{Junicode}
%-----------------------------------------
\usepackage[babelshorthands=true]{polyglossia}
\setmainlanguage[variant=ancient]{greek}
\setotherlanguages{italian,english}

\begin{document}
\section{Greek}

Junicode \u{ἄ} \={ἄ}

\fontspec{Brill}
Brill \u{ἄ} \={ἄ}

\fontspec{New Athena Unicode}
New Athena Unicode \u{ἄ} \={ἄ}

\section{Italian}
\fontspec{Junicode}
Junicode \u{ἄ} \={ἄ}

\fontspec{Brill}
Brill \u{ἄ} \={ἄ}

\fontspec{New Athena Unicode}
New Athena Unicode \u{ἄ} \={ἄ}
\end{document}

%%% Local Variables:
%%% coding: utf-8
%%% mode: latex
%%% TeX-engine: xetex
%%% TeX-output-dir: "build-breve"
%%% TeX-master: t
%%% End:
```

This is the result:
![Schermata del 2023-09-27 11-11-20](https://github.com/psb1558/Junicode-font/assets/1306260/a45b5807-9019-46f8-8a5f-e5e3b04f3d8c)


Unfortunately, I don't have sufficient technical skills in this aspect, so forgive me if I can't follow you and if I'm wrong in something.

**Comment by psb1558** [comment]
Now I'm confused about what you're actually looking for. In your first post you were asking about vowels with breathing mark and acute over a macron:
<img width="154" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/5b7590e3-db1b-4b30-b73d-ff150480e4ae">
But a LaTeX command like e.g. `\u{ἄ}` is surely asking for a breve positioned over precomposed alpha + breathing + acute (U+1F04), and Junicode and Brill are giving you exactly that (but NAU is not):
<img width="60" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/e8b77e83-eb38-4f90-b7c2-a3b539797f5f">
I don't know polyglossia very well, but if you do `\u{α}\char"0313\char"0301`, i.e. alpha + breve followed by breathing mark and acute, then you get this:
<img width="25" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/09f58856-ebd2-40bd-b7b3-7e3ffc225588">
In LibreOffice, what you're seeing here:
<img width="73" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/5428b625-197d-420b-ae2c-c387fe0c0632">
is an annoying thing that LibreOffice sometimes does, leaving a ghost of one character behind when you replace it with another. It is a purely graphical glitch, which (in my experience) disappears shortly, and in any case isn't reflected in a printout or PDF export. Within the blue selection box (also the bounding box), the result seems to be what you are looking for.

Now it's true that Junicode demands that the language be set to Greek, when the other fonts are okay with English or Italian. This is because the tonos/oxia is shaped differently in the italic face, and the substitution of the Greek shape for the other is triggered by the language tag. I notice that in the other fonts Greek-specific features are triggered only by the script, not the language tags. I am making that change in Junicode, with the result that it will no longer be necessary to specify the language (the script is detected automatically):
<img width="113" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/1bb3ad7b-1e70-498c-b924-2b0d7c6c886d">
But I have doubts about whether I am understanding the problems you are seeing and the output you want.

**Comment by Doc73** [comment]
Thanks for the explanation!
I usually use LaTeX, but sometimes also LibreOffice. Fortunately, I rarely need to write those characters in LibreOffice, which I use for less serious things.

The result I would like to achieve is to see breathings and accents **under** the longum/breve sign.

You suggestion to use `\u{α}\char"0313\char"0301` works very well with Junicode (only greek) and New Athena Unicode (greek + italian), doesn't work at all with Brill font, but has the defect that it requires remembering the codes of many diacritical signs.

It is also difficult, at least for me, to remember the keyboard shortcuts to print the longum/breve and for this reason I prefer to use the `\={}` or `\u{}` commands in LaTeX. :smile: 

I really don't know what to tell you. Now, thanks to your explanation, I know how it works, but if there are better solutions, I honestly can't say.

Evaluate for yourself what is the best thing to do. In the meantime, thank you very much for your patience!

**Comment by psb1558** [comment]
Thanks for this clarification. But if you want the breathing and accent under the breve or macron, Junicode seems to be delivering that with `\u{ἄ} \={ἄ}`. And if you want it the other way around, Junicode seems to be capable of that too. And it seems to be working the same way in LaTeX and LibreOffice. And in the next release it will be more convenient because you won't have to specify Greek as the language of the text.

Am I missing some issue here?

**Comment by Doc73** [comment]
No, no! I was wrong!
I meant I want breathing and accent **above** breve or macron.
You have to forgive me, but I got confused! :sob:

**Comment by Doc73** [comment]
Yes! It's a good idea!
Many thanks!

**Comment by psb1558** [comment]
I think we can count this as finished now. Reopen if any problems.
