### ISSUE TITLE
Question mark kerned too close to capital W and V.

### ISSUE THREAD

**Issue by eclecticfluff** [psb1558/Junicode-font#243]
While kerning pairs are probably needed between most capitals and question marks, these two almost look like a collision at a distance. 
![IMG_2326](https://github.com/psb1558/Junicode-font/assets/65306291/a87a6b08-853b-447c-8e00-1266ff466370)

**Comment by psb1558** [comment]
A year or so ago, I got hold of a semi-automated kerning program. The program, I suspect, was fine: it was just that I was unable to make it work properly. Long story short, I've been repairing the damage ever since. With some six thousand kerning pairs for each of six masters, it's something of a slog. So do continue to post kerning problems here: I'll be grateful for every one of them.

**Comment by psb1558** [comment]
This is fixed.
