### ISSUE TITLE
Junicode_Encoded_Char_List.tex gives different PDFs for XeTeX and LuaTeX

### ISSUE THREAD

**Issue by jsbien** [psb1558/Junicode-font#249]
Have a look at the last page. I think the XeTeX version is the correct one.

**Comment by psb1558** [comment]
That is . . . astonishing. Also very mysterious, because those upper-range characters that are going wrong in the encoded chars doc are also on p. 38 of the Junicode Manual, also compiled with LuaLaTeX, and those are correct. So what is making LuaLaTeX go wrong? Until I figure it out, I will be compiling that doc with XeTeX.

**Comment by alerque** [comment]
Chances are this is a font load path issue, and LuaLaTeX is finding an extra set of font files somewhere and mixing and matching versions.

**Comment by psb1558** [comment]
@alerque: Interesting. I'll look into this.

**Comment by kberry** [comment]
Marcel Krueger, one of the luaotfload maintainers, advised that using [Renderer=HarfBuzz] should give better results with lualatex. And in my simple test file with Janusz's PUA Junicode character, that worked. FWIW ...

**Comment by psb1558** [comment]
Yes, it's never a mistake to use HarfBuzz. When I revise the document, I'll also be switching the font from Junicode to Junicode VF (which I recommend to anyone using LuaTeX).

**Comment by psb1558** [comment]
Renderer=HarfBuzz fixes the problem absolutely.
