### ISSUE TITLE
Request for Latin Lambda

### ISSUE THREAD

**Issue by marrus-sh** [psb1558/Junicode-font#280]
As [Unicode 16.0 is now in Beta and the character repertoire is considered stable](https://blog.unicode.org), I’d like to request glyphs for three Latin characters which are new in that version :⁠—

- `U+A7DA LATIN CAPITAL LETTER LAMBDA`
- `U+A7DB LATIN SMALL LETTER LAMBDA`
- `U+A7DC LATIN CAPITAL LETTER LAMBDA WITH STROKE`

These characters are siblings to `U+019B LATIN SMALL LETTER LAMBDA WITH STROKE`, which is already in Junicode (but may warrant a redesign). They are needed for the orthographies of many languages in the Salishan and Wakashan language families (indigenous languages of the Pacific Northwest). While they are not medievalist letters, I am requesting them because Junicode is otherwise a fairly complete Latin‐script font.

[The original proposal for the characters](https://www.unicode.org/L2/L2023/23191-three-latin-additions.pdf) has lots of details on the design of these characters, but I will summarize the main points here :⁠—

- The lowercase can use either Greek contrast (as Junicode `U+019B` currently does) or be made more Latinate (in which case `U+019B` would need to be changed), at the discretion of the font author. The uppercase should have the form of a rotated Latin capital Y in either case, and the characters should be expected to appear beside other Latin glyphs, not Greek ones.

    <img width="565" alt="image" src="https://github.com/psb1558/Junicode-font/assets/3212430/0c359d62-174a-40e5-a02c-444a9a8b50a5">

- The stroke can be either a straight diagonal (currently used by Junicode `U+019B`), or a tilde, at the discretion of the font author.

    <img width="692" alt="image" src="https://github.com/psb1558/Junicode-font/assets/3212430/f53e9eff-dbf3-4ed1-9680-9c5046d40100">

- One diacritic is of particular importance to these characters: `U+0313 COMBINING COMMA ABOVE`.

    <img width="1014" alt="image" src="https://github.com/psb1558/Junicode-font/assets/3212430/fa883849-4988-4951-a0f4-49c63d50da0c">

**Comment by psb1558** [comment]
I'll be glad to add these, but I'm going to do the next release (2.07) first, since it is nearly ready.

**Comment by psb1558** [comment]
Here's a first go at these glyphs:
<img width="325" alt="image" src="https://github.com/psb1558/Junicode-font/assets/16215767/c05636ff-1033-4a6b-b280-98b9b1f05613">
Junicode's rule is that there has got to be a small cap wherever there are case-paired glyphs (I assume that any language that uses the Latin or Greek alphabet will occasionally want small caps).

I should mention that the new glyphs are not classified as Latin letters in the font, since glyph classes are managed automatically by the font-building software, which does not yet know about them. In practical terms, this means:

- No kerning for the new glyphs.
- No case-pairing (a word-processor's command to change the case of one of these glyphs won't work).
- Some editing actions, like double-clicking to select a word, may not work.

And there may be some other problems I haven't thought of. However, after the new glyphs appear in the relevant databases, these problems will disappear. That will happen some time after the release of Unicode 16 in September. Maybe quite a while after.

Comments, please.

**Comment by marrus-sh** [comment]
This looks good to me! The stress on the lowercase seems a bit monotone, but that might actually be a good compromise in this case (Greek letter used in a Latin context), so I don’t have a problem with it.

**Comment by psb1558** [comment]
These glyphs are in the new release, version 2.209.
