### ISSUE TITLE
Ctrl+Shift+B resulting Exp SmBold instead of Bold in Indesign

### ISSUE THREAD

**Issue by rikzafsh** [psb1558/Junicode-font#282]
I am using Indesign 2020 and Windows 11. When I press Ctrl+Shift+B in Indesign, it makes Junicode Regular becomes Exp SmBold instead of Bold. However, if the text has been set to Bold, pressing Ctrl+Shift+B will make the text become Regular.
![Screenshot 2024-06-07 171421](https://github.com/psb1558/Junicode-font/assets/93246199/a0332506-874b-49ed-bb07-40d2b13a9872)

**Comment by kenmcd** [comment]
What version of the fonts?
Variable or statics?

**Comment by rikzafsh** [comment]
Latest version, but earlier version is also like that.
I use static font.
Indesign 2019 and 2020.
Windows 10 and 11 (I use two different laptop and still have the same problem).

**Comment by kenmcd** [comment]
> Latest version

Which "latest version" specifically?

**Comment by psb1558** [comment]
I'm getting a different effect: the shortcut for bold type does nothing at all in my copy of InDesign. It does work with Elstob. I'll check over the style linking.

**Comment by kenmcd** [comment]
> The problem was a stray parameter that was messing up the style linking (I'm not sure how).

What did you find?
I checked and did see the issue, so I am curious.

**Comment by kenmcd** [comment]
Hmmmm... quite odd.
I do not see any STAT table in the Normal/Regular or the Exp/SmBold (although they could have one).
Since this change has fixed the issue, I really wonder what it was.
So I will be interested in running a diff with the working fonts to see what changed.

**Comment by psb1558** [comment]
Right. I also checked for a STAT table and didn't find one. So my theory is that the presence of the parameter somehow caused fontmake either to not do style linking at all when generating the fonts or to do it improperly. After all, a STAT table does the job that style linking does, but in a more modern way. But I'm far from certain.

**Comment by psb1558** [comment]
Looked at the fsSelection and macStyle bits in the current and the next version and saw no difference. So as of now I have no idea what I broke before or what I have fixed.

**Comment by kenmcd** [comment]
You know I love a good mystery... :-)
I saw nothing wrong with the static fonts style-linking so I am intrigued.
It could just be an InDesign issue.
This only involves the statics, and the few I checked have no STAT tables - so that does not appear to be the issue.
But maybe I should see if any of them have a STAT table.

Maybe only some (or one) of the static fonts had a STAT table (from your "Style name as STAT entry" setting).
And I wonder if the user had the variable also installed - but that should not matter as the family name includes the "VF."

Part of my curiosity is I am trying to get really familiar with `STAT` entries, and `fvar` instances, and style-linking in variable fonts.
Like I am with static fonts.
I want to be able to just look at it and see the issues.
I'm on a quest!

Gonna go run a ttx STAT dump on the whole static directory and see if it shows any STAT tables in the statics.

**Comment by psb1558** [comment]
I did a ttx dump on the whole static otf directory and found no STAT table in any of them. Didn't check the ttf, though.

**Comment by kenmcd** [comment]
> I did a ttx dump on the whole static otf directory and found no STAT table in any of them. Didn't check the ttf, though.

OK.

**Comment by psb1558** [comment]
The (mysteriously) fixed fonts should now be in the new release, 2.209.
