### ISSUE TITLE
Failure to apply tracking to certain strings

### ISSUE THREAD

**Issue by fr-peter** [psb1558/Junicode-font#292]
I am using junicodevf in the latest TeX Live distribution. When using small capitals, I have found that words containing the string "ectio" do not have the desired tracking (provided by the microtype package) applied. Minimum working example:
```
% !TEX TS-program = lualatex
\documentclass{article}
\usepackage{junicodevf}
% behaviour also happens when using the non-variable version. does not happen if either junicode package is not used.
\usepackage[tracking=true]{microtype}


\begin{document}
\scshape I found that the word “section” does not have proper tracking. After some testing, it's not just section, but any word with the string “ectio” in it will fail to have proper tracking.

electioneering deflection: in these examples, “lection” is does not have proper tracking, but the other characters do.

Interestingly, putting a hyphen, en-dash, or em-dash immediately before or after the affected word will cause it to appear properly: section-electioneering---selection

\end{document}
```
![image](https://github.com/user-attachments/assets/bfdf8d64-11ed-4883-8182-7d773fb61acc)

**Comment by fr-peter** [comment]
Upon further tinkering, it appears the issue has something to do with HarfBuzz. The following works as expected:
```
% !TEX TS-program = lualatex
\documentclass{article}

\usepackage{fontspec}
\setmainfont{JunicodeVF}
\usepackage[tracking=true]{microtype}

\begin{document}
\scshape I found that the word “section” does not have proper tracking. After some testing, it's not just section, but any word with the string “ectio” in it will fail to have proper tracking.

electioneering deflection: in these examples, “lection” does not have proper tracking, but the other characters do.

Interestingly, putting a hyphen, en-dash, or em-dash immediately before or after the affected word will cause it to appear properly: section-electioneering---selection

\end{document}
```
However, replacing `\setmainfont{JunicodeVF}` with `\setmainfont{JunicodeVF}[Renderer=HarfBuzz]` produces the improper letterspacing. This doesn't impact other fonts I tried this with. `\setmainfont{Alegreya}[Renderer=HarfBuzz]` works as expected.

**Comment by psb1558** [comment]
This one is fantastically, deliciously bizarre. I can say confidently that tracking is not a function of the font at all, though it seems that there is something in JunicodeVF that interferes with the way microtype does tracking—but **only when the option "Renderer=Harfbuzz" is present in the fontspec command that sets the font**. That accounts for the difference between loading the font with the junicodevf package and loading it without: the junicodevf package *always* uses the Harfbuzz renderer, as it must do to provide reliable access to all of Junicode's OpenType commands.

I have no idea what in Junicode is tripping up fontspec or microtype or Harfbuzz, and I am really not equipped to do that kind of testing of multiple (substantial and complex) packages. So don't look for a fix here.

But I have found a workaround for you, and it's a good one (i.e. not too awfully kludgy). Just define a font instance that 1.) loads JunicodeVF without the Harfbuzz renderer; 2.) turns on small caps for the instance; 3.) uses fontspec's `LetterSpace` option for tracking instead of microtype. This will do it:
```
\setfontface\tracksc{JunicodeVF}[
  SmallCapsFont={*},
  Letters=SmallCaps,
  LetterSpace=12.0,
  Ligatures=TeX
]
```
(Of course, you need to adjust the `LetterSpace` number to get the tracking you want.) Then use the `\tracksc` command to turn on your spaced small caps instead of `\scshape`. It will look like this:
<img width="627" alt="image" src="https://github.com/user-attachments/assets/f3c6a7ba-0762-4787-8669-5d5d61792a2e">
Here is your file with the fix:
```
% !TEX TS-program = lualatex
\documentclass{article}
\usepackage{junicodevf}
% behaviour also happens when using the non-variable version. does not
% happen if either junicode package is not used.]
%\usepackage[tracking=true]{microtype}
\setfontface\tracksc{JunicodeVF}[
  SmallCapsFont={*},
  Letters=SmallCaps,
  LetterSpace=12.0,
  Ligatures=TeX
]

\begin{document}
\tracksc I found that the word “section” does not have proper tracking. After some testing, it's not just section, but any word with the string “ectio” in it will fail to have proper tracking.

electioneering deflection: in these examples, “lection” is does not
have proper tracking, but the other characters do.

Interestingly, putting a hyphen, en-dash, or em-dash immediately before or after the affected word will cause it to appear properly: section-electioneering---selection

\end{document}
```
(Your last note rolled in just a few minutes ago, after I had written almost all the above, and I see you discovered the bit about Harfbuzz. This workaround will let you do your tracking and also get all the other benefits of the `junicodevf` package. If you need sequences of small caps with other weights or widths, just define more font instances.)

**Comment by fr-peter** [comment]
Wow, thanks for the speedy reply. And thanks for the great typeface!

**Comment by psb1558** [comment]
Glad to help!

**Comment by khaledhosny** [comment]
This should be reported to either luaotfload or microtype (or both). The code that uses HarfBuzz in luaotfload is quite different from the default mode, and either luaotfload is doing something wrong or microtype is making some assumption that is not true when HarfBuzz is used.

**Comment by fr-peter** [comment]
Okay, I will go ahead and report it to both luaotfload and microtype.

**Comment by psb1558** [comment]
Thanks, @khaledhosny  and @fr-peter. I was wondering whether to report this and if so where: but now I see I don't have to!

**Comment by alerque** [comment]
Following this with curiosity... I see I'm a bit late posting this since the bug has been *claimed*, but I did run a quick test to see if SILE would be affected by this given that it uses HarfBuzz as well and has similar knobs to fiddle with.

Here is a roughly equivalent MWE to be saved as `junicode.sil`:

```sile
\begin[papersize=a5]{document}
\font[family=Junicode,features=+smcp,size=12pt]
\set[parameter=shaper.tracking,value=1.15]
I found that the word “section” does not have proper tracking. After some testing, it's not just section, but any word with the string “ectio” in it will fail to have proper tracking.

electioneering deflection: in these examples, “lection” does not have proper tracking, but the other characters do.

Interestingly, putting a hyphen, en-dash, or em-dash immediately before or after the affected word will cause it to appear properly: section-electioneering—selection
\end{document}
```

Then rendered with:

```console
$ sile junicode.sil
SILE v0.15.4 (LuaJIT 2.1.1700206165) [Rust]
</home/caleb/scratch/junicode.sil> as sil
[1]
```

The result has normal tracking throughout:

![image](https://github.com/user-attachments/assets/d32a8134-c9cb-4137-b941-8a9dff3aee1a)

**Comment by psb1558** [comment]
Thanks, Caleb! Does SILE use luaotfload? Because the luaotfload folks seem to have claimed it as their bug.

**Comment by alerque** [comment]
No it doesn't, it uses `fontconfig` and `harfbuzz` directly via their C bindings. I worked up that MWE before the `luaotfload` folks claimed responsibility and just got distracted before the posting was done. I posted it anyway for comparison, but clearly it doesn't have any relevance to the luaotfload issue.

**Comment by psb1558** [comment]
It's useful to know.
