### ISSUE TITLE
Hinting question

### ISSUE THREAD

**Issue by Sunspark-007** [psb1558/Junicode-font#293]
Made this an issue instead of a discussion because it might be one if it ends up creating a new file or workflow.

To recap, the status of the build as it is today, static ttf in the current release is the last ttfautohinted one being released, the static otf uses the deprecated psautohint (afdko tools prefer otfautohint now), the variable ttf uses manual hinting to some degree.

Rendering differences in LibreOffice on a Linux desktop: The variable font can't be used because of a problem with LO itself--always displays the wrong style. Static otf and static ttf are relatively the same shape but the regular weight ttf appears to be a touch darker so it is better in that aspect for screen display. I've kept a Junicode Two Beta otf around which is unhinted and it looks completely different in LO.. the x-height is higher and "e" etc. looks more spacious. 

I don't know if the glyphs were redrawn from the beta to be shorter, or if the taller more open appearance is a result of not being hinted. 

I would like to suggest for consideration trying out otfautohint in the newer afdko package to see how that output looks, and also, to explore the possibility of providing an unhinted static version to see how that looks as well.

For proper pixel display of the images below you need to open them in a new tab and scale your browser to the correct zoom factor (67% on a display set to 150%) or copy them into paint. They really do look like two different typefaces.

75% zoom 12 point on a display that is logically scaled to 150% (top is beta, bottom is ttf static):
![image](https://github.com/user-attachments/assets/2c7b0c5d-f636-4e61-ab8b-08454336614f)

100% zoom 12 point on a display that is logically scaled to 150% (top is beta, bottom is ttf static):
![image](https://github.com/user-attachments/assets/f078ee4f-2330-4d48-b3d7-417ff3dd736c)

120% zoom 12 point on a display that is logically scaled to 150% (top is beta, bottom is ttf static):
![image](https://github.com/user-attachments/assets/4892f70c-f7db-46a7-b8d6-f929d02c2757)

**Comment by psb1558** [comment]
I wasn't aware of what was happening with psautohint. I'll certainly look into otfautohint, which looks to be the same thing, merged into the AFDKO package.

Glyph outlines in Junicode have not changed since the beta, except for the usual corrections, adjustments, etc. Any differences you see are almost certainly due to different kinds of hinting. I don't see these differences as a problem unless one uses different versions together on the same project.

For various reasons I am trying to reduce the number of versions I am delivering, so I'm not eager to add unhinted versions to the Junicode package. There are tools about for deleting hints from a font, and it should be easy to build Junicode without hints on a Linux system (instructions on the [Junicode page](https://github.com/psb1558/Junicode-font)).

**Comment by psb1558** [comment]
There is nothing to do here, I think.
