### ISSUE TITLE
Subsetting Historic Ligatures

### ISSUE THREAD

**Issue by bryankaplan** [psb1558/Junicode-font#295]
Is it possible to specify a subset of `hlig`? If so, how?

**Comment by psb1558** [comment]
Are you using pyftsubset from fontTools? I ask because this is the only tool I've made much use of, and it allows fine control of your subsetting.

**Comment by bryankaplan** [comment]
`pyftsubset` looks quite useful, and it may well answer this question. I don't know yet.

But I may have chosen the wrong word when I said “subset”. Provided a non-subsetted junicode font, is it possible to indicate some (and only some) of the sub-features of `hlig`?

**Comment by psb1558** [comment]
Ah. I see. Sorry, but I don't know of any way to make `hist` work that way. The feature has just got to be on when you want it and off when you don't. I don't need it myself, but I can see that it could be a pain to use.

**Comment by psb1558** [comment]
I have been thinking, actually, of offering an alternative way of getting these ligatures: by placing U+200D zero width joiner between two characters. Then the three-character sequence could be resolved in `liga` Standard Ligatures instead of in `hist`. This might make it easier to get individual ligatures without having to turn a feature on and off, possibly disrupting kerning and contextual alternates.

**Comment by bryankaplan** [comment]
The ZWJ idea is smart, and I'm sure if you add it, some people will use it.

That being said, for covering an entire text it's generally easier to enable a feature. I just wish they could be enabled individually.

**Comment by eclecticfluff** [comment]
If you can use LuaLaTeX for your document, `selnolig` readily covers this problem with the `\nolig` macro.

**Comment by psb1558** [comment]
I think there is nothing to do here.
