### ISSUE TITLE
Combining Grave and Acute are not displayed correctly

### ISSUE THREAD

**Issue by rikzafsh** [psb1558/Junicode-font#296]
I'm using Junicode VF version 2.209 InDesign 2020, Windows 11.
The combining grave accent (U+0300) and combining accute accent (U+0301) are not displayed correctly when combined with some basic Latin letters.

I also want to suggest to add characters from Latin Extended-E block, especially U+AB49
![Screenshot 2024-08-20 194818](https://github.com/user-attachments/assets/5fb91129-0c18-46fb-867d-bba32fe29d09)

**Comment by psb1558** [comment]
I'll add U+AB49. If you want others from Latin Extended E, list them here.

InDesign's default OpenType handling is extremely buggy, and Junicode, because it has a large number of OT features (some of them rather complex) tends to bring out those bugs. If you switch to the Adobe World-Ready Paragraph Composer, the accents will be correctly positioned.

InDesign 2020 is pretty old. You might also get better results if you upgrade.

**Comment by rikzafsh** [comment]
I tried to upgrade to Indesign 2024 and it works. Thank you.

I want U+AB35, AB36, AB38, AB3A, AB3B, AB3C, AB46, AB48, AB49, AB4A, AB4B, AB4C, AB4D, AB53, AB54, AB56, and AB58
