### ISSUE TITLE
long s followed by k

### ISSUE THREAD

**Issue by Hawke** [psb1558/Junicode-font#303]
Junicode generally seems to do the right thing with regard to long s.

However, I did find one situation that it seems to get “wrong“: 'sk' should perhaps be rendered with the round s as seen here in 'Muskets'. Of course there may be historical counterexamples too …
 
![image](https://github.com/user-attachments/assets/0a1a256c-95f0-445d-b2b4-48fbac51a6a3)

**Comment by psb1558** [comment]
You may be right. I've only checked one source (First Folio, since it's easy to search), but those printers, anyway, seem not to have had an ſk ligature in their font. I'll do some more research. In the meantime, you can use a ZWNJ (U+200C) to break that ligature.

**Comment by psb1558** [comment]
It seems to me that printers will use an ſk ligature if they have it in the font--but not all do. Here, for example, is from Ben Franklin's press, 1752:
<img width="396" alt="image" src="https://github.com/user-attachments/assets/8454d4c8-357f-4cb1-882c-8b9dcec101fe">
At present I think no change is appropriate, since it is easy to break the ligature if you don't want it.
