### ISSUE TITLE
Issue with "ki"; Italic legacy font

### ISSUE THREAD

**Issue by sakkamade** [psb1558/Junicode-font#59]
Sample:
![image](https://user-images.githubusercontent.com/62730422/125227576-a97ce700-e2c2-11eb-8962-55b3d3cf6692.png)
There is no such problem with old Junicode, and there is no such problem with "ko", "ka", "ke" etc.

**Comment by psb1558** [comment]
It isn't a bug, but a design decision that turned out not to be popular (that ligature is pretty common in old prints using italics: I must have seen it in the Fell pica that Junicode is based on).

Obviously it should have been in dlig instead of liga. I'll see if I can fix it using TTX. It's a tremendous can of worms at this point to fix things any other way.

**Comment by psb1558** [comment]
That was easy, and the font validates. So I've pushed the new Junicode-Italic.

**Comment by sakkamade** [comment]
> ... that ligature is pretty common in old prints using italics ...

I could find nothing of the sort, perhaps you can provide some examples? since――

> ... I must have seen it in the Fell pica that Junicode is based on.

――the only Fell Pica I could find is [IM FELL DW Pica](https://fonts.adobe.com/fonts/im-fell-dw-pica), and this is how "ki" appears there:

![Screenshot_2](https://user-images.githubusercontent.com/62730422/125360318-624f2e80-e374-11eb-888f-86b72b4d9334.jpg)

and [IM FELL Double Pica](https://fonts.adobe.com/fonts/im-fell-double-pica), which also has a common "ki."

**Comment by psb1558** [comment]
I wish I had made a note about it at the time (whenever that was). I would never have come up with a ligature like that on my own: I must have had a model. But the model would be a 17th or 18th-century printed book, not a modern font (I never look at Igino Marini's Fell fonts—not closely, anyway—because I don't want to be accused of violating anyone's copyright).

I haven't been able to find my model for the ki ligature, but if I do, I'll post an image here.

**Comment by sakkamade** [comment]
Thank you!

I guess this issue should be left open for now; for I am always glad to see something peculiar, but I honestly thought that it has been unintentional change.
