### ISSUE TITLE
Please tag releases

### ISSUE THREAD

**Issue by alerque** [psb1558/Junicode-font#65]
It would be a lot easier for distro packages to get this distributed in package repositories if the Git repository here had tags matching the release versions. Following the OpenFV convention either use `vX.YYY` or `X.YYY` tags on the commit that is considered the official release of the fonts at that version. This will avoid packaging with mix-matched versions across distros claiming to be the same thing because packages had to sort through and randomly pick a commit themselves, and also reduce the size of downloads they have to do to package correctly.

(Arch Linux is currently stuck on the Juincode legacy builds released (with tagged versions) on Sourforge. I'll add a package for the new series as soon as this issue is addressed. Additionally if you have any input as to whether the legacy font series should be kept or completely replaced by this let me know. We could potentially drop it and add fontconfig rules to the packaging to help the font name transition. I'm inclined to just keep the legacy version and add this for people to transition as they feel like, but if there are zero metric changes from the legacy series I would talk to the packager of the legacy version (cc: @escondida) and we could consider alternatives.)

**Comment by psb1558** [comment]
Okay. I hope you can advise me here, because this repo has both old Junicode (current version: 1.003) and the heavily revised JuniusX/JuniusVF (curren version: 1.011). It was probably a bad idea to do it this way, but I didn't want to mess with SourceForge any more, since GitHub seemed more usable.

Am I right that a tag marks the entire repo and not just the files in an individual commit, so that if I put in a "v1.003" tag, that will be (wrongly) tagging JuniusX as well as legacy Junicode?

If so, would it be better (more helpful to you and packagers generally) to remove the legacy Junicode files from here and create a new Junicode-Legacy repository? That could have regular tagged releases (few and far between, since I'm only fixing bugs there and not adding features).

I would suggest to package maintainers that they keep (old) Junicode in their distros, not replacing it with JuniusX/VF, because many documents will be broken if users simply change the font from Junicode to JuniusX.

As to packaging JuniusX, I'm of two minds about that. There's no release through the GitHub release system because it is still unstable. I don't run every version through the various testing apps, and in general I am open to fairly radical revisions between versions (like the recent revision of the cvNN features). And, of course, there's no italic yet. So the whole thing is very much a use-at-your-own-risk deal (meant in a more serious way than the standard disclaimer at the end of the OFL license). So I'm not sure if it's a good idea to package it for Arch Linux (or any of the other distros) at this point.

**Comment by alerque** [comment]
Thanks for the background. That will take a little ... unraveling. Let me poke around a bit and come up with a recommendation or two. You might assign this issue to me just in case my attention gets lost.

**Comment by psb1558** [comment]
Okay, done (I think). Sorry my repos are so messy.

**Comment by lvcivs** [comment]
I would recommend to put old Junicode in a separate repository, e.g. "Junicode-legacy", as it has a different versioning and a different release cadence.

**Comment by psb1558** [comment]
Thanks, @lvcivs. That's my inclination too. Will see if @alerque has further thoughts.

**Comment by folknor** [comment]
> So the whole thing is very much a use-at-your-own-risk deal. So I'm not sure if it's a good idea to package it for Arch Linux at this point.

The files are already published here in the repository, and they're already useful to a range of different people (thank you!), so why not make accessing them easier? Some people might not realise you can download a GH repo as a zip file even when there are no releases - they might download each TTF file individually. Also, they might not understand that the `fonts` folder contains 3 different releases of the font at the moment (as far as I can tell), plus the `webfiles` folder has yet another release, potentially 2.

I think it would be helpful if the disclaimer in your README that the font isn't finished was almost at the top of the document, instead of close to the bottom. And most of what you said in the comment here about unstability isn't in the README at all.

I always think that more knowledge is better. Inform users, and let them decide.

**Comment by alerque** [comment]
I think I'm going to have to side with @lvcivs and suggest two repositories are better if there are going to be two font families going forward. However, that depends a little bit on whether the legacy family will even see any development at all. If it might get patched, then having it's own repo where it can proceed at it's own cadence will be easiest downstream. If it is officially dead and deprecated but still kept for legacy purposes, then we can probably come up with a satisfactory legacy tag scheme to keep it out of the way but still available.

There are other alternatives no matter, but lets here what the plan is for the legacy font family before bothering to elaborate on what they might be.

**Comment by psb1558** [comment]
First of all, I'm sorry about the confusion of running two versions of what is (looked at the way many users will look at it) one font in one repository under two different names. When I launched the JuniusX project my thinking was that the differences from the existing Junicode font were going to be radical enough that it would make sense for a lot of users to have both installed. That actually becomes more true every time I make a commit. As for the presence of legacy Junicode in the same respository, I was simply looking for a convenient place to put it and didn't think about it much.

Now as to the status of legacy Junicode: I decided for various reasons that I would add no new features (including glyphs) to that font, but only to JuniusX.  Junicode will receive bug fixes, but that's all. Appropriately for this mission, the "source" for Junicode is now a TTX file (in which it is easy to fix bugs but hard to introduce new features) instead of FontForge + Adobe .fea files (they remain on SourceForge, but I've abandoned that whole workflow). I envision Junicode sticking around because of the number of documents set in it, but I'll encourage anyone starting a new project to use JuniusX.

That is, once JuniusX is production-ready. It's not there yet.

**Comment by psb1558** [comment]
As the matter of tagging also involves naming, this applies also to issue #66.

It occurs to me that I've been too fussy about naming—led astray by the fact that I've never loved the name "Junicode." But it's been around a long time, lots of people know it well, and retaining it will make it clear what people are getting when they download the new version.

I think what I should do is 

- retain the name "Junicode" for the version that is in progress here;
- make a release of the current legacy Junicode with its version (v1.003) as a tag;
- rename JuniusX to Junicode and JuniusVF to JunicodeVF, and
- bump the release number to 2.0

This, I think, will conform to conventions that everyone understands and avoid the necessity of creating a new repository. Bumping to the next major version number makes (I think) the radical changes in the OT code okay. It will simplify the lives of packagers.

The only problem is breaking a number of existing documents with changes to the OT code. I can survey the code to see if I can spot ways to mitigate the damage without excessively compromising what I'm trying to do with the new version.

Coments? Suggestions?

**Comment by kenmcd** [comment]
Sounds like a great idea.
Simplifies everything here.
Benefits from the long-time Junicode name recognition.
The bump to v2.0 goes along with the [semantic versioning](https://semver.org/) (also used by GF).
_"MAJOR version when you make incompatible API changes,"_
Would not worry too much about incompatibility of new features.
Just add info to the readme.md and other docs to explain.

**Comment by marrus-sh** [comment]
Worth noting that this is roughly the policy used by SIL for their fonts; see for example <https://software.sil.org/lcgfonts/charis-doulos-gentium-andika-v6-000/>…

So I think it is okay.

Regarding legacy Junicode, I hesitate to suggest that it might be easiest to create a separate branch containing only the legacy files, and then tag `v1.XXX` releases from that branch. Only because if it *is* patched in the future, it will avoid the (potentially confusing) situation of having a v1 release appear after a v2 release on the same branch.

**Comment by psb1558** [comment]
Thanks, @kenmcd and @marrus-sh. Good to know that this is the custom elsewhere.

Also, @marrus-sh, thanks for the tip about the new branch. I suppose this is actually the kind of situation branches are for.

(Now all I have to do is figure out how to use them ...)

**Comment by psb1558** [comment]
Different branches for versions 1 and 2 still seem a decent idea. I've been reading about branches and thinking about things like directory layout and naming.

The contents (including the directory structure) of the two branches would be quite different, since the workflows for the two versions are quite different, so that at this point there's not even overlap in the codebases. Some might think this problematic. GitHub lets you protect a branch so that it is at least much more difficult to create havoc by inadvertently merging.

Is it okay to have directories with the same name (e.g. Source, Fonts, Docs) but different content in the two branches? And is it okay to run essentially unrelated series of tags in two branches of the same repository?

**Comment by sakkamade** [comment]
You can add the commit that creates a branch of "Version 1", where you can remove everything unrelated to version 1 (or leave it as is), and then make that branch a "default" one, since in README you stated that it is still a current stable version. 

There is nothing wrong with version 1 and version 2 to be in the same repository.

> Is it okay to have directories with the same name (e.g. Source, Fonts, Docs) but different content in the two branches? 

Of course.

> And is it okay to run essentially unrelated series of tags in two branches of the same repository?

Certainly; there are plenty of such situations. 
Take a look here https://github.com/arvidn/libtorrent, as an example.

**Comment by Rhialto** [comment]
I'm coming here also with my packaging hat on. I'm with [pkgsrc](https://pkgsrc.org/), and for now I have updated this font's package also to version 1.002 from SourceForge, like @alerque in his original post. I would love to package 1.003 when there is a release or tag for it, and also the new version.

**Comment by psb1558** [comment]
I have now created a Junicode-One branch with everything removed except those things related to the current stable version (1.003). I.ve added the latest version of the documentation for old Junicode (Tex and PDF). I've tagged a release (v1.003).

I have also removed Junicode One files from the master repository., though I have done no tagging there.

**Comment by alexmyczko** [comment]
the 1.003 tagged release is without source of fonts, but the fonts already as ttf. why?

**Comment by psb1558** [comment]
I'm no longer working from the original FontForge sources (still parked at SourceForge), but from TTX files, which are in /legacy/ttx. (I put them there to avoid confusion with the new version.) I can move them to a new sources folder, but the history (of which there is admittedly not much) will be obscured.

**Comment by alexmyczko** [comment]
Please accept my excuse then. Looking forward for the new verson...

**Comment by psb1558** [comment]
Glad to move things around if that makes it easier for packagers . . .

**Comment by alexmyczko** [comment]
no need to waste time moving things around. just the information that ttx is the new source, is perfect. thank you for this excellent font (and the others too), btw.

**Comment by psb1558** [comment]
Thanks, @alexmyczko.

**Comment by alexmyczko** [comment]
could you enlighten me how they work? preferably non interactive and cli

**Comment by psb1558** [comment]
I'm an old Open Source guy: I've always preferred OS software (I felt I had to switch from FontForge to Glyphs because one can work at least twice as fast in Glyphs, and it handles multiple masters/interpolation well), and I regard building natively with Glyphs as a stopgap and building with the Open Source cli tool [fontmake](https://github.com/googlefonts/fontmake) as the goal. This is how it worked with [Elstob](https://github.com/psb1558/Elstob-font), for which you can see the build script (bash) and supporters (XSLT, Python) in the sources folder (I know, not a very modern-looking build process, but I hate learning new toolchains).

With Junicode, which is much bigger and more complicated than Elstob, it's harder to make a version that is buildable with fontmake, which has requirements somewhat different from those of Glyphs (for example, it crashes when it encounters Glyphs' hints). However, about a week ago, when I decided that I had to have a cff2-flavored variable font to work with LuaTeX, I managed to get it working, and I recorded the steps needed to do it in the "note" section of the Italic Glyphs source (Junicode-Italic.glyphspackage/fontinfo.plist). I don't think all those steps can be scripted at present but being able to build with fontmake at all is a positive step.

Sorry for all the verbiage, but I'm working up to a question (since I don't do packaging), namely how you'd like the sources to look. Some OS font projects provide UFOs along with Glyphs files: would that be best? Do you use my (messy, amateurish) scripts or do your own? Google Fonts is now prescribing a particular directory structure and toolchain: does theirs work for you?

Couple of final points: (1) my files are Glyphs 3, but they're fine with fontmake (maybe because I don't use a lot of Glyphs 3 features). (2) Since the beyond-beta versions will always be built with fontmake, no need to worry about the difference between fonts built with commercial software and those built with Open Source software.

**Comment by Rhialto** [comment]
I can only speak from pkgsrc, but probably other package systems are similar in regard. Pkgsrc is mainly for building software, and because much of those use the pattern of `configure`, `make`, `make install`, it's kind of optimized for packages that work that way. 
But not everything does, of course, so then it is common to replace the commands in those phases with something else (or nothing). Sometimes it is enough to add some commands before or after the standard phase (for example, to run `autoreconf` before `configure`).

If the package has nothing useful that fits in this pattern, then pkgsrc would simply put a bunch of custom commands instead of the `make` and/or `make install` phase. Of course that isn't the preferred way to do things, because then it becomes the packager's job to keep this up to date.

Creating a package is done with a staged install: the package's `make install` copies all the needed files to `${DESTDIR}${PREFIX}`. `${DESTDIR}` is some temporary directory. Its contents is put in an archive and at install time it's extracted, so that the files end up in `${PREFIX}`. If a package remembers file or directory names somewhere, it should include the `${PREFIX}` but not the `${DESTDIR}` part.

For fonts, pkgsrc at least has some particular place where it wants them, which may differ from other systems. So for fonts the upstream install phase is relatively often heavily patched or even ignored and rewritten.

So to get to the point, for building it is easiest if there is just one script to run. It could have a ton of parameters, or environment variables to be set, that is not a problem and can easily be done.

**Comment by psb1558** [comment]
Thanks, @Rhialto! This is a help. So far it seems to me that what I did for Elstob is about right: provide sources in a form that fontmake can use without alteration (either .glyphs or .ufo) plus whatever scripts I develop for my own use. Packagers can use the scripts or supply their own, but the important thing would seem to be the condition of the source--that it should be ready for fontmake.
